# Generated by Django 3.1.4 on 2021-01-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('where', models.CharField(max_length=100, null=True)),
                ('descrbtion', models.CharField(max_length=100, null=True)),
                ('info', models.CharField(max_length=100, null=True)),
                ('kind', models.CharField(max_length=30, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('Images', models.ImageField(null=True, upload_to='')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.city')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.user')),
            ],
        ),
        migrations.CreateModel(
            name='howToGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wayOfTransport', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.user')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.place')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('givenRate', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('commrate', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.user')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.place')),
            ],
        ),
    ]
