# Generated by Django 3.1.4 on 2021-01-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20210113_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descrbtion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='city',
            name='shortDescribtion',
        ),
    ]
