# Generated by Django 3.1.4 on 2021-01-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20210118_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='howtogo',
            name='wayOfTransport',
        ),
    ]
