# Generated by Django 3.1.4 on 2021-01-18 06:56

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_auto_20210118_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='canSee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commrate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='Images',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='canSee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rateCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.kind'),
        ),
    ]
