# Generated by Django 3.1.4 on 2021-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20210118_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
