# Generated by Django 3.1.4 on 2021-01-19 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0008_auto_20210118_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='wayOfTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commrate',
        ),
        migrations.AddField(
            model_name='comment',
            name='commrate',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='howtogo',
            name='wayOfTransport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.wayoftransport'),
        ),
    ]
